### ISSUE TITLE
`ImportAttribute` type error with v1.7.9

### ISSUE THREAD

**Issue by chetbox** [sarsamurmu/estree-toolkit#22]
After upgrading from v1.7.8 to v1.7.9 I get the following Typescript error which is failing my build:

```
node_modules/jexl-to-estree/node_modules/estree-toolkit/dist/generated/builders-type.d.ts:1:1233 - error TS2305: Module '"estree-jsx"' has no exported member 'ImportAttribute'.

1 import { Identifier, Literal, Program, FunctionDeclaration, FunctionExpression, ArrowFunctionExpression, SwitchCase, CatchClause, VariableDeclarator, ExpressionStatement, BlockStatement, EmptyStatement, DebuggerStatement, WithStatement, ReturnStatement, LabeledStatement, BreakStatement, ContinueStatement, IfStatement, SwitchStatement, ThrowStatement, TryStatement, WhileStatement, DoWhileStatement, ForStatement, ForInStatement, ForOfStatement, VariableDeclaration, ClassDeclaration, ThisExpression, ArrayExpression, ObjectExpression, YieldExpression, UnaryExpression, UpdateExpression, BinaryExpression, AssignmentExpression, LogicalExpression, MemberExpression, ConditionalExpression, CallExpression, NewExpression, SequenceExpression, TemplateLiteral, TaggedTemplateExpression, ClassExpression, MetaProperty, AwaitExpression, ImportExpression, ChainExpression, Property, Super, TemplateElement, SpreadElement, ObjectPattern, ArrayPattern, RestElement, AssignmentPattern, ClassBody, MethodDefinition, ImportDeclaration, ExportNamedDeclaration, ExportDefaultDeclaration, ExportAllDeclaration, ImportSpecifier, ImportDefaultSpecifier, ImportNamespaceSpecifier, ExportSpecifier, PrivateIdentifier, PropertyDefinition, StaticBlock, ImportAttribute, JSXIdentifier, JSXNamespacedName, JSXMemberExpression, JSXEmptyExpression, JSXExpressionContainer, JSXSpreadAttribute, JSXAttribute, JSXClosingElement, JSXClosingFragment, JSXElement, JSXFragment, JSXOpeningElement, JSXOpeningFragment, JSXSpreadChild, JSXText } from 'estree-jsx';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ~~~~~~~~~~~~~~~

node_modules/jexl-to-estree/node_modules/estree-toolkit/dist/generated/builders-type.d.ts:51:85 - error TS2339: Property 'options' does not exist on type 'ImportExpression'.

51     importExpression(source: ImportExpression['source'], options?: ImportExpression['options']): ImportExpression;
                                                                                       ~~~~~~~~~

node_modules/jexl-to-estree/node_modules/estree-toolkit/dist/generated/builders-type.d.ts:63:136 - error TS2339: Property 'attributes' does not exist on type 'ImportDeclaration'.

63     importDeclaration(specifiers: ImportDeclaration['specifiers'], source: ImportDeclaration['source'], attributes?: ImportDeclaration['attributes']): ImportDeclaration;
                                                                                                                                          ~~~~~~~~~~~~

node_modules/jexl-to-estree/node_modules/estree-toolkit/dist/generated/builders-type.d.ts:64:210 - error TS2339: Property 'attributes' does not exist on type 'ExportNamedDeclaration'.

64     exportNamedDeclaration(declaration: ExportNamedDeclaration['declaration'], specifiers?: ExportNamedDeclaration['specifiers'], source?: ExportNamedDeclaration['source'], attributes?: ExportNamedDeclaration['attributes']): ExportNamedDeclaration;
                                                                                                                                                                                                                    ~~~~~~~~~~~~

node_modules/jexl-to-estree/node_modules/estree-toolkit/dist/generated/builders-type.d.ts:66:145 - error TS2339: Property 'attributes' does not exist on type 'ExportAllDeclaration'.

66     exportAllDeclaration(source: ExportAllDeclaration['source'], exported?: ExportAllDeclaration['exported'], attributes?: ExportAllDeclaration['attributes']): ExportAllDeclaration;
                                                                                                                                                   ~~~~~~~~~~~~

node_modules/jexl-to-estree/node_modules/estree-toolkit/dist/generated/is-type.d.ts:2:1233 - error TS2305: Module '"estree-jsx"' has no exported member 'ImportAttribute'.

2 import { Identifier, Literal, Program, FunctionDeclaration, FunctionExpression, ArrowFunctionExpression, SwitchCase, CatchClause, VariableDeclarator, ExpressionStatement, BlockStatement, EmptyStatement, DebuggerStatement, WithStatement, ReturnStatement, LabeledStatement, BreakStatement, ContinueStatement, IfStatement, SwitchStatement, ThrowStatement, TryStatement, WhileStatement, DoWhileStatement, ForStatement, ForInStatement, ForOfStatement, VariableDeclaration, ClassDeclaration, ThisExpression, ArrayExpression, ObjectExpression, YieldExpression, UnaryExpression, UpdateExpression, BinaryExpression, AssignmentExpression, LogicalExpression, MemberExpression, ConditionalExpression, CallExpression, NewExpression, SequenceExpression, TemplateLiteral, TaggedTemplateExpression, ClassExpression, MetaProperty, AwaitExpression, ImportExpression, ChainExpression, Property, Super, TemplateElement, SpreadElement, ObjectPattern, ArrayPattern, RestElement, AssignmentPattern, ClassBody, MethodDefinition, ImportDeclaration, ExportNamedDeclaration, ExportDefaultDeclaration, ExportAllDeclaration, ImportSpecifier, ImportDefaultSpecifier, ImportNamespaceSpecifier, ExportSpecifier, PrivateIdentifier, PropertyDefinition, StaticBlock, ImportAttribute, JSXIdentifier, JSXNamespacedName, JSXMemberExpression, JSXEmptyExpression, JSXExpressionContainer, JSXSpreadAttribute, JSXAttribute, JSXClosingElement, JSXClosingFragment, JSXElement, JSXFragment, JSXOpeningElement, JSXOpeningFragment, JSXSpreadChild, JSXText } from 'estree-jsx';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ~~~~~~~~~~~~~~~

node_modules/jexl-to-estree/node_modules/estree-toolkit/dist/generated/types.d.ts:2:1263 - error TS2305: Module '"estree-jsx"' has no exported member 'ImportAttribute'.

2 export { SimpleLiteral, RegExpLiteral, Identifier, Literal, Program, FunctionDeclaration, FunctionExpression, ArrowFunctionExpression, SwitchCase, CatchClause, VariableDeclarator, ExpressionStatement, BlockStatement, EmptyStatement, DebuggerStatement, WithStatement, ReturnStatement, LabeledStatement, BreakStatement, ContinueStatement, IfStatement, SwitchStatement, ThrowStatement, TryStatement, WhileStatement, DoWhileStatement, ForStatement, ForInStatement, ForOfStatement, VariableDeclaration, ClassDeclaration, ThisExpression, ArrayExpression, ObjectExpression, YieldExpression, UnaryExpression, UpdateExpression, BinaryExpression, AssignmentExpression, LogicalExpression, MemberExpression, ConditionalExpression, CallExpression, NewExpression, SequenceExpression, TemplateLiteral, TaggedTemplateExpression, ClassExpression, MetaProperty, AwaitExpression, ImportExpression, ChainExpression, Property, Super, TemplateElement, SpreadElement, ObjectPattern, ArrayPattern, RestElement, AssignmentPattern, ClassBody, MethodDefinition, ImportDeclaration, ExportNamedDeclaration, ExportDefaultDeclaration, ExportAllDeclaration, ImportSpecifier, ImportDefaultSpecifier, ImportNamespaceSpecifier, ExportSpecifier, PrivateIdentifier, PropertyDefinition, StaticBlock, ImportAttribute, JSXIdentifier, JSXNamespacedName, JSXMemberExpression, JSXEmptyExpression, JSXExpressionContainer, JSXSpreadAttribute, JSXAttribute, JSXClosingElement, JSXClosingFragment, JSXElement, JSXFragment, JSXOpeningElement, JSXOpeningFragment, JSXSpreadChild, JSXText } from 'estree-jsx';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ~~~~~~~~~~~~~~~
```

**Comment by sarsamurmu** [comment]
Please check with the new version I have just released

Actual issue is that this package need `@types/estree` of version `1.0.7`, and in your project it was not updated because this package didn't specify it correctly. You can try reinstalling this package if the new version does not work.

**Comment by chetbox** [comment]
Thanks. That seems to have solved the type issues after updating both `estree-toolkit` and `@types/estree`.
